### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by dee-y** [BeauRussell/OpenSourceBot#2]
Hello, am a graphic designer and i would like to contribute a logo to your project. This offer is free of course.

**Comment by BeauRussell** [comment]
I don't see where this logo would be displayed, there's no UI built for the client

**Comment by dee-y** [comment]
Oh i see, it could also be displayed on your git page readme just to make
project finer :)

**Comment by BeauRussell** [comment]
If you want to make a design you can and I'll take a look

**Comment by dee-y** [comment]
Hi, what do you think of this concept? any color modifications you would like me to make? if you like it, what sizes do you need and files?

![streamme-01-01](https://user-images.githubusercontent.com/36637989/43292477-616c712c-912d-11e8-9ec2-689e34259c32.png)

**Comment by BeauRussell** [comment]
https://info.stream.me/brand-assets/ For information on the logos and colors
